#ifndef PIN_DEFINITIONS_H
#define PIN_DEFINITIONS_H

#define BRAKE_LEVER_POT_PIN 13

#define SERVO_BRAKE_FRONT_PIN 44
#define SERVO_BRAKE_BACK_PIN 36


#define NIGHT_LIGHT_BUTTON_PIN 4
#define HORN_BUTTON_PIN 12
#define HAND_BRAKE_BUTTON_PIN 2
#define HAND_BRAKE_LED_PIN 10

#define BRAKE_LIGHT_MOSFET_PIN 35
#define NIGHT_LIGHT_MOSFET_PIN 18
#define HORN_MOSFET_PIN 16


#define SPEED_SENSOR_PIN 11

#endif
